<?php

declare(strict_types=1);

namespace BnplPartners\Factoring004Magento\Controller\Adminhtml\Otp;

use Magento\Backend\App\Action;
use Magento\Backend\App\Action\Context;
use Magento\Backend\Model\Session;
use Magento\Backend\Model\UrlInterface;
use Magento\Framework\App\RequestInterface;
use Magento\Framework\Exception\LocalizedException;
use Magento\Framework\View\Element\AbstractBlock;
use Magento\Framework\View\Result\PageFactory;

class Index extends Action
{
    public const ADMIN_RESOURCE = 'BnplPartners_Factoring004::admin';

    /**
     * @var PageFactory
     */
    private $resultPageFactory;

    /**
     * @var \Magento\Backend\App\Action
     */
    private $saveAction;

    /**
     * @var \Magento\Backend\Model\Session
     */
    private $session;

    public function __construct(
        Context $context,
        PageFactory $resultPageFactory,
        Session $session
    ) {
        parent::__construct($context);

        $this->resultPageFactory = $resultPageFactory;
        $this->saveAction = $this->createAction();
        $this->session = $session;

        // We should substitute params before call any methods on shipment action
        if ($this->getRequest()->isPost()) {
            $this->substituteRequestParamsFromSession();
        }
    }

    protected function _getSession()
    {
        if ($this->getRequest()->isPost()) {
            return $this->saveAction->_getSession();
        }

        return parent::_getSession();
    }

    public function dispatch(RequestInterface $request)
    {
        if ($this->getRequest()->isPost()) {
            return $this->saveAction->dispatch($request);
        }

        return parent::dispatch($request);
    }

    public function getUrl($route = '', $params = [])
    {
        if ($this->getRequest()->isPost()) {
            return $this->saveAction->getUrl($route, $params);
        }

        return parent::getUrl($route, $params);
    }

    protected function _isAllowed()
    {
        if ($this->getRequest()->isPost()) {
            return $this->saveAction->_isAllowed();
        }

        return parent::_isAllowed();
    }

    protected function getMessageManager()
    {
        if ($this->getRequest()->isPost()) {
            return $this->saveAction->getMessageManager();
        }

        return parent::getMessageManager();
    }

    protected function _setActiveMenu($itemId)
    {
        if ($this->getRequest()->isPost()) {
            return $this->saveAction->_setActiveMenu($itemId);
        }

        return parent::_setActiveMenu($itemId);
    }

    protected function _addBreadcrumb($label, $title, $link = null)
    {
        if ($this->getRequest()->isPost()) {
            return $this->saveAction->_addBreadcrumb($label, $title, $link);
        }

        return parent::_addBreadcrumb($label, $title, $link);
    }

    protected function _addContent(AbstractBlock $block)
    {
        if ($this->getRequest()->isPost()) {
            return $this->saveAction->_addContent($block);
        }

        return parent::_addContent($block);
    }

    protected function _addLeft(AbstractBlock $block)
    {
        if ($this->getRequest()->isPost()) {
            return $this->saveAction->_addLeft($block);
        }

        return parent::_addLeft($block);
    }

    protected function _addJs(AbstractBlock $block)
    {
        if ($this->getRequest()->isPost()) {
            return $this->saveAction->_addJs($block);
        }

        return parent::_addJs($block);
    }

    protected function _isUrlChecked()
    {
        if ($this->getRequest()->isPost()) {
            return $this->saveAction->_isUrlChecked();
        }

        return parent::_isUrlChecked();
    }

    protected function _processLocaleSettings()
    {
        if ($this->getRequest()->isPost()) {
            return $this->saveAction->_processLocaleSettings();
        }

        return parent::_processLocaleSettings();
    }

    protected function _redirect($path, $arguments = [])
    {
        if ($this->getRequest()->isPost()) {
            return $this->saveAction->_redirect($path, $arguments);
        }

        return parent::_redirect($path, $arguments);
    }

    protected function _forward($action, $controller = null, $module = null, array $params = null)
    {
        parent::_forward($action, $controller, $module, $params); // TODO: Change the autogenerated stub
    }

    protected function _validateSecretKey()
    {
        if ($this->getRequest()->isPost()) {
            return $this->saveAction->_validateSecretKey();
        }

        return parent::_validateSecretKey();
    }

    public function getActionFlag()
    {
        if ($this->getRequest()->isPost()) {
            return $this->saveAction->getActionFlag();
        }

        return parent::getActionFlag();
    }

    public function _processUrlKeys()
    {
        if ($this->getRequest()->isPost()) {
            return $this->saveAction->_processUrlKeys();
        }

        return parent::_processUrlKeys();
    }

    /**
     * @throws \Exception
     */
    public function execute()
    {
        if ($this->getRequest()->isPost()) {
            return $this->saveAction->execute();
        }

        return $this->resultPageFactory->create();
    }

    private function substituteRequestParamsFromSession(): void
    {
        $params = $this->session->getData('factoring004_' . $this->getDoAction() . '_data') ?? [];

        $this->getRequest()->setParams(array_merge($params, [
            'form_key' => $this->getRequest()->getParam('form_key'),
            'key' => $this->saveAction->_backendUrl->getSecretKey(),
        ]));
    }

    /**
     * @throws \Magento\Framework\Exception\LocalizedException
     */
    private function createAction(): Action
    {
        throw new LocalizedException(__('Unsupported action given'));
    }

    private function getDoAction(): string
    {
        return $this->getRequest()->getParam('fields', ['do' => 'shipment'])['do'];
    }
}
